'use client';

import { ChangeEvent, useMemo, useState } from 'react';
import { createId, ProjectTask } from '../lib/storage';

type Screen = string;
type Attachment = { id: string; file: File; name: string; type: string; size: number };
type IntakeProject = { id: string; title: string; deadline: string; description: string; rubricText: string; attachments: Attachment[]; tasks: ProjectTask[]; currentTaskIndex: number };
const allowedTypes = ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain', 'image/png', 'image/jpeg'];
const maxFileSize = 10 * 1024 * 1024;
const mockTasks = (): ProjectTask[] => [
  ['Choose a research question', 'Pick a focused question you want to explore.', '20 min'], ['Find reliable sources', 'Save three useful articles or studies.', '35 min'], ['Review Chapter 3', 'Take notes on the most relevant concepts.', '30 min'], ['Create an outline', 'Put your main points in a simple order.', '25 min'], ['Write a first draft', 'Draft the introduction and first section.', '45 min']
].map(([title, description, estimatedTime], index) => ({ id: createId('task'), title, description, estimatedTime, position: index + 1, completed: false, completedAt: null }));
const newProject = (): IntakeProject => ({ id: createId('project'), title: '', deadline: '', description: '', rubricText: '', attachments: [], tasks: mockTasks(), currentTaskIndex: 0 });
const formatSize = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const formatType = (file: File) => file.name.split('.').pop()?.toUpperCase() ?? 'FILE';

function Primary({ children, onClick, disabled = false, type = 'button' }: { children: React.ReactNode; onClick?: () => void; disabled?: boolean; type?: 'button' | 'submit' }) { return <button type={type} disabled={disabled} onClick={onClick} className="min-h-12 w-full rounded-2xl bg-gradient-to-r from-[#744CC3] to-[#59369F] px-5 py-3 font-bold text-white shadow-sm disabled:cursor-not-allowed disabled:opacity-40">{children}</button>; }
function Secondary({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) { return <button type="button" onClick={onClick} className="min-h-12 w-full rounded-2xl border border-[#D8D1E2] bg-white px-4 py-3 font-semibold text-[#443D50] hover:bg-[#F5F1FA]">{children}</button>; }
function Header({ back }: { back?: () => void }) { return <header className="mb-7 flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-2"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-plum text-white">⌁</div><b className="truncate text-xl">NeuroPath</b></div>{back && <button type="button" onClick={back} className="shrink-0 rounded-xl px-3 py-2 text-sm font-semibold text-plum hover:bg-lavender">Back</button>}</header>; }
function Shell({ children, back }: { children: React.ReactNode; back?: () => void }) { return <main className="mx-auto min-h-screen max-w-xl overflow-x-hidden px-5 py-6 pb-28 sm:px-7 sm:pb-16"><Header back={back} />{children}</main>; }
function TaskNode({ task, current }: { task: ProjectTask; current: boolean }) { const state = task.completed ? 'Completed.' : current ? 'Current task · Today' : `Upcoming · Step ${task.position}`; return <div className="relative flex gap-4 pb-6"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-plum text-sm font-bold text-white">{task.completed ? '✓' : task.position}</div><div className={`min-w-0 flex-1 rounded-2xl p-4 ${current ? 'bg-gradient-to-r from-[#EEE8FB] to-[#F6F1FF] ring-2 ring-[#D8C9F5]' : task.completed ? 'bg-[#EDF5EE]' : 'bg-[#F1EEF2] text-[#746C7C]'}`}><div className="flex flex-wrap justify-between gap-x-3 gap-y-1"><b className="break-words">{task.title}</b><span className="text-xs font-semibold">{task.estimatedTime}</span></div><p className="mt-1 text-sm">{state}</p></div></div>; }
function FileList({ attachments, onRemove }: { attachments: Attachment[]; onRemove?: (id: string) => void }) { if (!attachments.length) return <p className="rounded-2xl bg-[#F1EEF2] p-4 text-sm text-[#655E6D]">No files attached.</p>; return <ul className="space-y-2">{attachments.map((attachment) => <li key={attachment.id} className="flex min-w-0 items-start gap-3 rounded-2xl bg-white p-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-lavender text-xs font-bold text-plum">{formatType(attachment.file)}</span><div className="min-w-0 flex-1"><p className="break-all font-semibold leading-5">{attachment.name}</p><p className="mt-1 break-words text-xs text-[#655E6D]">{attachment.type || formatType(attachment.file)} · {formatSize(attachment.size)}</p></div>{onRemove && <button onClick={() => onRemove(attachment.id)} className="shrink-0 rounded-lg px-2 py-1 text-sm font-semibold text-plum">Remove</button>}</li>)}</ul>; }
function PlanTaskCard({ task, index, total, expanded, onToggle, onMove, onDelete, onChange }: { task: ProjectTask; index: number; total: number; expanded: boolean; onToggle: () => void; onMove: (direction: -1 | 1) => void; onDelete: () => void; onChange: (field: 'title' | 'description' | 'estimatedTime', value: string) => void }) { return <article className="card"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold text-plum">STEP {task.position}</p><h2 className="mt-1 break-words font-bold">{task.title}</h2><p className="mt-1 break-words text-sm text-[#655E6D]">{task.description}</p><p className="mt-2 text-sm font-semibold text-[#655E6D]">{task.estimatedTime}</p></div><button onClick={onToggle} aria-expanded={expanded} className="shrink-0 rounded-xl bg-lavender px-3 py-2 text-sm font-bold text-plum">{expanded ? 'Close' : 'Edit'}</button></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => onMove(-1)} disabled={index === 0} aria-label={`Move Step ${task.position} up`} className="rounded-lg border border-[#D8D1E2] px-3 py-2 text-sm font-bold text-plum disabled:cursor-not-allowed disabled:border-[#E8E4EB] disabled:bg-[#F1EEF2] disabled:text-[#9B94A2]">↑</button><button onClick={() => onMove(1)} disabled={index === total - 1} aria-label={`Move Step ${task.position} down`} className="rounded-lg border border-[#D8D1E2] px-3 py-2 text-sm font-bold text-plum disabled:cursor-not-allowed disabled:border-[#E8E4EB] disabled:bg-[#F1EEF2] disabled:text-[#9B94A2]">↓</button><button onClick={onDelete} className="rounded-lg px-3 py-2 text-sm font-bold text-[#9A3C47]">Delete</button></div>{expanded && <div className="mt-4 border-t border-[#EEEAF2] pt-4"><label className="block"><span className="label">Task title</span><input className="field" value={task.title} onChange={(e) => onChange('title', e.target.value)} /></label><label className="mt-3 block"><span className="label">Short description</span><textarea className="field min-h-20" value={task.description} onChange={(e) => onChange('description', e.target.value)} /></label><label className="mt-3 block"><span className="label">Estimated time</span><input className="field" value={task.estimatedTime} onChange={(e) => onChange('estimatedTime', e.target.value)} /></label></div>}</article>; }

export default function Home() {
  const [screen, setScreen] = useState<Screen>('dashboard');
  // Single shared active-session structure. Files remain in memory and are never uploaded.
  const [project, setProject] = useState<IntakeProject>(newProject);
  const [fileError, setFileError] = useState(''); const [message, setMessage] = useState(''); const [energy, setEnergy] = useState(''); const [reflection, setReflection] = useState(''); const [expandedTaskId, setExpandedTaskId] = useState<string | null>(null);
  const tasks = useMemo(() => [...project.tasks].sort((a, b) => a.position - b.position), [project.tasks]);
  const currentTask = tasks.find((task) => !task.completed);
  const hasActiveProject = Boolean(project.title.trim());
  const hasCurrentTask = hasActiveProject && tasks.length > 0 && Boolean(currentTask);
  const go = (next: Screen) => { setScreen(next); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const updateProject = (field: keyof IntakeProject, value: string) => setProject((current) => ({ ...current, [field]: value }));
  const validDetails = Boolean(project.title.trim() && project.deadline);
  const selectFiles = (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); const accepted: Attachment[] = []; const errors: string[] = []; files.forEach((file) => { const duplicate = project.attachments.some((item) => item.name === file.name && item.size === file.size && item.file.lastModified === file.lastModified); if (!allowedTypes.includes(file.type)) errors.push(`${file.name}: unsupported file type.`); else if (file.size > maxFileSize) errors.push(`${file.name}: file exceeds the 10 MB limit.`); else if (duplicate) errors.push(`${file.name}: already attached.`); else accepted.push({ id: createId('file'), file, name: file.name, type: file.type, size: file.size }); }); setProject((current) => ({ ...current, attachments: [...current.attachments, ...accepted] })); setFileError(errors.join(' ')); event.target.value = ''; };
  const removeFile = (id: string) => setProject((current) => ({ ...current, attachments: current.attachments.filter((item) => item.id !== id) }));
  const reorder = (id: string, direction: -1 | 1) => setProject((current) => { const ordered = [...current.tasks].sort((a, b) => a.position - b.position); const index = ordered.findIndex((task) => task.id === id); const target = index + direction; if (target < 0 || target >= ordered.length) return current; [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; return { ...current, tasks: ordered.map((task, position) => ({ ...task, position: position + 1 })), currentTaskIndex: 0 }; });
  const updateTask = (id: string, field: keyof Pick<ProjectTask, 'title' | 'description' | 'estimatedTime'>, value: string) => setProject((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === id ? { ...task, [field]: value } : task) }));
  const removeTask = (id: string) => setProject((current) => ({ ...current, tasks: current.tasks.filter((task) => task.id !== id).sort((a, b) => a.position - b.position).map((task, index) => ({ ...task, position: index + 1 })), currentTaskIndex: 0 }));
  const addTask = () => setProject((current) => ({ ...current, tasks: [...current.tasks, { id: createId('task'), title: 'New task', description: 'Add a short description.', estimatedTime: '15 min', position: current.tasks.length + 1, completed: false, completedAt: null }] }));
  const usePlan = () => { setProject((current) => ({ ...current, tasks: current.tasks.sort((a, b) => a.position - b.position).map((task, index) => ({ ...task, position: index + 1, completed: false, completedAt: null })), currentTaskIndex: 0 })); setMessage('Plan saved. Step 1 is ready when you are.'); go('map'); };
  const completeTask = () => { if (!currentTask) return; setProject((current) => { const updated = current.tasks.map((task) => task.id === currentTask.id ? { ...task, completed: true, completedAt: new Date().toISOString() } : task); const index = updated.sort((a, b) => a.position - b.position).findIndex((task) => !task.completed); return { ...current, tasks: updated, currentTaskIndex: index }; }); go('reflection'); };
  const resetForNewProject = () => { setProject(newProject()); setFileError(''); setMessage(''); go('create'); };
  if (screen === 'planReview') return <Shell back={() => go('detailsReview')}><p className="eyebrow">PROPOSED PLAN</p><h1 className="mt-1 break-words text-3xl font-bold">{project.title}</h1><p className="mt-2 text-sm text-[#615A6B]">Placeholder task data for this prototype — not AI generated.</p><div className="mt-6 space-y-4">{tasks.length ? tasks.map((task, index) => <PlanTaskCard key={task.id} task={task} index={index} total={tasks.length} expanded={expandedTaskId === task.id} onToggle={() => setExpandedTaskId((current) => current === task.id ? null : task.id)} onMove={(direction) => reorder(task.id, direction)} onDelete={() => { removeTask(task.id); setExpandedTaskId((current) => current === task.id ? null : current); }} onChange={(field, value) => updateTask(task.id, field, value)} />) : <div className="rounded-2xl bg-[#F1EEF2] p-5 text-sm text-[#655E6D]">No tasks in this proposed plan. Add a task to continue.</div>}</div><div className="mt-5"><Secondary onClick={addTask}>Add task</Secondary></div><div className="mt-8 space-y-3"><Primary disabled={!tasks.length} onClick={usePlan}>Use this plan</Primary><Secondary onClick={() => go('detailsReview')}>Back to review details</Secondary></div></Shell>;
  if (screen === 'dashboard') return <Shell><p className="text-[#615A6B]">Good afternoon, Maya.</p><h1 className="mt-1 text-3xl font-bold tracking-tight">One small step is enough.</h1>{message && <div role="status" className="mt-5 rounded-2xl bg-sage p-4 text-sm font-semibold text-[#24533B]">✓ {message}</div>}{hasCurrentTask && <section className="mt-6 rounded-3xl bg-gradient-to-br from-[#6E48BD] to-[#4F3293] p-6 text-white"><p className="text-sm font-semibold text-[#E5DDF9]">TODAY’S SESSION</p><h2 className="mt-3 break-words text-2xl font-bold">{currentTask?.title}</h2><p className="mt-1 text-[#E5DDF9]">{project.title} · {currentTask?.estimatedTime}</p><div className="mt-6"><Primary onClick={() => go('energy')}>Start session</Primary></div></section>}<div className="mt-9 flex items-center justify-between gap-4"><h2 className="text-xl font-bold">Active project</h2><button onClick={resetForNewProject} className="shrink-0 font-bold text-plum">Create project</button></div>{!hasActiveProject ? <article className="card mt-4"><b>No project created yet</b><p className="mt-3 text-sm text-[#615A6B]">Create a project to see your plan.</p></article> : !tasks.length ? <article className="card mt-4"><b>{project.title}</b><p className="mt-3 text-sm text-[#615A6B]">Your plan has no tasks yet.</p><button onClick={() => go('planReview')} className="mt-3 font-bold text-plum">Edit plan</button></article> : <article className="card mt-4"><div className="flex justify-between gap-3"><b className="break-words">{project.title}</b><b className="text-plum">{Math.round((tasks.filter((task) => task.completed).length / tasks.length) * 100)}%</b></div><p className="mt-3 text-sm text-[#615A6B]">{currentTask ? `Next: ${currentTask.title}` : 'Project complete'}</p></article>}</Shell>;
  if (screen === 'dashboard') return <Shell><p className="text-[#615A6B]">Good afternoon, Maya.</p><h1 className="mt-1 text-3xl font-bold tracking-tight">One small step is enough.</h1>{message && <div role="status" className="mt-5 rounded-2xl bg-sage p-4 text-sm font-semibold text-[#24533B]">✓ {message}</div>}<section className="mt-6 rounded-3xl bg-gradient-to-br from-[#6E48BD] to-[#4F3293] p-6 text-white"><p className="text-sm font-semibold text-[#E5DDF9]">TODAY’S SESSION</p><h2 className="mt-3 break-words text-2xl font-bold">{currentTask?.title ?? 'Create a project to begin'}</h2><p className="mt-1 text-[#E5DDF9]">{project.title || 'NeuroPath'} · {currentTask?.estimatedTime ?? 'one small step'}</p><div className="mt-6 space-y-3"><Primary disabled={!currentTask || !project.title} onClick={() => go('energy')}>Start session</Primary><button disabled={!currentTask || !project.title} onClick={() => go('session')} className="min-h-11 w-full rounded-2xl border border-white/30 font-semibold disabled:opacity-40">I can’t start</button></div></section><div className="mt-9 flex items-center justify-between gap-4"><h2 className="text-xl font-bold">Active project</h2><button onClick={resetForNewProject} className="shrink-0 font-bold text-plum">Create project</button></div><article className="card mt-4"><div className="flex justify-between gap-3"><b className="break-words">{project.title || 'No project created yet'}</b><b className="text-plum">{tasks.length ? `${Math.round((tasks.filter((task) => task.completed).length / tasks.length) * 100)}%` : '—'}</b></div><p className="mt-3 text-sm text-[#615A6B]">{project.title ? `Next: ${currentTask?.title ?? 'Project complete'}` : 'Create a project to see your plan.'}</p></article></Shell>;
  if (screen === 'create') return <Shell back={() => go('dashboard')}><p className="eyebrow">NEW PROJECT</p><h1 className="mt-1 text-3xl font-bold">Let’s make a clear plan.</h1><p className="mt-2 text-[#615A6B]">Attachments stay only in this browser session for this prototype.</p><form onSubmit={(event) => { event.preventDefault(); if (validDetails) go('detailsReview'); }} className="mt-7 space-y-6"><label><span className="label">Project title</span><input required className="field" value={project.title} onChange={(e) => updateProject('title', e.target.value)} />{!project.title && <span className="mt-1 block text-sm text-[#9A3C47]">A title is required.</span>}</label><label><span className="label">Deadline</span><input required type="date" className="field" value={project.deadline} onChange={(e) => updateProject('deadline', e.target.value)} />{!project.deadline && <span className="mt-1 block text-sm text-[#9A3C47]">A deadline is required.</span>}</label><label><span className="label">Project description or instructions</span><textarea className="field min-h-28" value={project.description} onChange={(e) => updateProject('description', e.target.value)} /></label><label><span className="label">Pasted rubric <span className="font-normal">(optional)</span></span><textarea className="field min-h-28" value={project.rubricText} onChange={(e) => updateProject('rubricText', e.target.value)} /></label><div><span className="label">Supporting files <span className="font-normal">(optional)</span></span><label className="block cursor-pointer rounded-2xl border-2 border-dashed border-[#D8D1E2] bg-white p-5 text-center font-semibold text-plum"><input type="file" multiple accept=".pdf,.docx,.txt,.png,.jpg,.jpeg,application/pdf,text/plain,image/png,image/jpeg" className="sr-only" onChange={selectFiles} />Choose files · PDF, DOCX, TXT, PNG, JPG · up to 10 MB each</label><p className="mt-2 text-xs text-[#655E6D]">Prototype behavior: files are not uploaded or analyzed.</p>{fileError && <p role="alert" className="mt-2 text-sm font-semibold text-[#9A3C47]">{fileError}</p>}<div className="mt-3"><FileList attachments={project.attachments} onRemove={removeFile} /></div></div><Primary type="submit" disabled={!validDetails}>Review details</Primary></form></Shell>;
  if (screen === 'detailsReview') return <Shell back={() => go('create')}><p className="eyebrow">REVIEW DETAILS</p><h1 className="mt-1 text-3xl font-bold">Check your project details.</h1><div className="mt-7 space-y-4"><article className="card"><p className="text-sm font-semibold text-plum">TITLE</p><p className="mt-1 font-bold">{project.title}</p></article><article className="card"><p className="text-sm font-semibold text-plum">DEADLINE</p><p className="mt-1">{project.deadline}</p></article><article className="card"><p className="text-sm font-semibold text-plum">DESCRIPTION</p><p className="mt-1 whitespace-pre-wrap text-sm">{project.description || 'No description provided.'}</p></article><article className="card"><p className="text-sm font-semibold text-plum">RUBRIC</p><p className="mt-1 whitespace-pre-wrap text-sm">{project.rubricText || 'No rubric provided.'}</p></article><div><p className="label">Attached files</p><FileList attachments={project.attachments} /></div></div><div className="mt-7 space-y-3"><Primary onClick={() => go('planReview')}>Continue to proposed plan</Primary><Secondary onClick={() => go('create')}>Edit details</Secondary></div></Shell>;
  if (screen === 'planReview') return <Shell back={() => go('detailsReview')}><p className="eyebrow">PROPOSED PLAN</p><h1 className="mt-1 break-words text-3xl font-bold">{project.title}</h1><p className="mt-2 text-sm text-[#615A6B]">Placeholder task data for this prototype — not AI generated.</p><div className="mt-6 space-y-4">{tasks.length ? tasks.map((task, index) => <article key={task.id} className="card"><div className="flex items-center justify-between gap-2"><b>Step {task.position}</b><div className="flex gap-1"><button onClick={() => reorder(task.id, -1)} disabled={index === 0} className="rounded-lg px-2 py-1 text-sm font-bold text-plum disabled:opacity-30">↑</button><button onClick={() => reorder(task.id, 1)} disabled={index === tasks.length - 1} className="rounded-lg px-2 py-1 text-sm font-bold text-plum disabled:opacity-30">↓</button><button onClick={() => removeTask(task.id)} className="rounded-lg px-2 py-1 text-sm font-bold text-[#9A3C47]">Delete</button></div></div><label className="mt-3 block"><span className="sr-only">Task title</span><input className="field" value={task.title} onChange={(e) => updateTask(task.id, 'title', e.target.value)} /></label><label className="mt-2 block"><span className="sr-only">Task description</span><textarea className="field min-h-20" value={task.description} onChange={(e) => updateTask(task.id, 'description', e.target.value)} /></label><label className="mt-2 block"><span className="sr-only">Estimated time</span><input className="field" value={task.estimatedTime} onChange={(e) => updateTask(task.id, 'estimatedTime', e.target.value)} /></label></article>) : <div className="rounded-2xl bg-[#F1EEF2] p-5 text-sm text-[#655E6D]">No tasks in this proposed plan. Add a task to continue.</div>}</div><div className="mt-5"><Secondary onClick={addTask}>Add task</Secondary></div><div className="mt-7 space-y-3"><Primary disabled={!tasks.length} onClick={usePlan}>Use this plan</Primary><Secondary onClick={() => go('create')}>Return to project details</Secondary></div></Shell>;
  if (screen === 'map') return <Shell back={() => go('dashboard')}><p className="eyebrow">PROJECT MAP</p><h1 className="mt-1 break-words text-3xl font-bold">{project.title}</h1><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-3"><Secondary onClick={() => go('create')}>Edit project details</Secondary><Secondary onClick={() => go('detailsReview')}>View attached files</Secondary><Secondary onClick={() => go('planReview')}>Edit plan</Secondary></div><div className="mt-7">{tasks.map((task) => <TaskNode key={task.id} task={task} current={task.id === currentTask?.id} />)}</div><Primary disabled={!currentTask} onClick={() => go('energy')}>Start current task</Primary></Shell>;
  if (screen === 'energy') return <Shell back={() => go('map')}><p className="eyebrow">ENERGY CHECK-IN</p><h1 className="mt-1 text-3xl font-bold">How are you feeling today?</h1><div className="mt-7 grid grid-cols-2 gap-3">{['Focused', 'Okay', 'Low energy', 'Overwhelmed'].map((level) => <button key={level} onClick={() => setEnergy(level)} className={`min-h-24 rounded-2xl p-4 text-left font-bold ${energy === level ? 'bg-lavender text-plum ring-2 ring-plum' : 'bg-white'}`}>{level}</button>)}</div><div className="mt-8"><Primary disabled={!energy} onClick={() => go('session')}>Continue</Primary></div></Shell>;
  if (screen === 'session') return <Shell back={() => go('map')}><p className="eyebrow">TODAY’S SESSION · {energy}</p><h1 className="mt-1 break-words text-3xl font-bold">{currentTask?.title}</h1><p className="mt-2 text-[#615A6B]">Estimated time: {currentTask?.estimatedTime}</p><div className="mt-7 space-y-3">{['Open your notes', 'Read the first paragraph', 'Write one useful idea'].map((step) => <label key={step} className="flex gap-3 rounded-2xl bg-white p-4"><input type="checkbox" />{step}</label>)}</div><div className="mt-8"><Primary onClick={completeTask}>Complete session</Primary></div></Shell>;
  return <Shell back={() => go('dashboard')}><p className="eyebrow">REFLECTION</p><h1 className="mt-1 text-3xl font-bold">How did that session feel?</h1><div className="mt-7 space-y-3">{['Easier than expected', 'About right', 'Harder than expected'].map((option) => <button key={option} onClick={() => setReflection(option)} className={`min-h-14 w-full rounded-2xl px-4 text-left font-semibold ${reflection === option ? 'bg-lavender text-plum ring-2 ring-plum' : 'bg-white'}`}>{option}</button>)}</div><div className="mt-7"><Primary disabled={!reflection} onClick={() => { setMessage('Session completed. The next task is ready.'); go('dashboard'); }}>Save reflection</Primary></div></Shell>;
}
